version: "3.9"
services:
  backend:
    build: "./packages/backend"
    container_name: backend
    depends_on:
      - database
    environment:
      - MONGO_DB_URI=mongodb://admin:secret123@database:27017
    ports:
      - "3000:3000"
  database:
    image: mongo
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret123
    ports:
      - "27017:27017"
